[build]
  base = "client"
  command = "npm run build"
  publish = "client/.next"

[context.production.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_CACHE = "true"
